name: Deploy RDS with Terraform

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.6

    - name: Configure AWS credentials
      run: |
        echo ${{ secrets.TF_VAR_AWS_ACCESS_KEY_ID }} > aws_access_key
        echo ${{ secrets.TF_VAR_AWS_SECRET_ACCESS_KEY }} > aws_secret_key
        aws configure set aws_access_key_id $(cat aws_access_key)
        aws configure set aws_secret_access_key $(cat aws_secret_key)
      env:
        AWS_DEFAULT_REGION: us-east-1  # Change to your region
        AWS_ACCESS_KEY_ID: ${{ secrets.TF_VAR_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_VAR_AWS_SECRET_ACCESS_KEY }}
        DB_USERNAME: ${{ secrets.TF_VAR_DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.TF_VAR_DB_PASSWORD }}

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform Changes
      run: terraform plan -var="tf_var_aws_access_key_id=${{ secrets.TF_VAR_AWS_ACCESS_KEY_ID }}" -var="tf_var_aws_secret_acess_key=${{ secrets.TF_VAR_AWS_SECRET_ACCESS_KEY }}" -var="tf_var_db_username=${{ secrets.TF_VAR_DB_USERNAME }}" -var="tf_var_db_password=${{ secrets.TF_VAR_DB_PASSWORD }}" -input=false -out=tfplan

    - name: Apply Terraform Changes
      run: terraform apply -input=false -auto-approve tfplan
